import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { dark } from '@clerk/themes'
import { ClerkProvider,ClerkLoaded,ClerkLoading } from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ClerkLoading>
            <h1 className="flex w-full h-screen text-2xl font-medium justify-center items-center">Loading...</h1>
          </ClerkLoading>
          <ClerkLoaded>
          <Navbar />
          {children}
          </ClerkLoaded>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
